### ISSUE TITLE
Crashes Bitwig's audio engine

### ISSUE THREAD

**Issue by spectromas** [ssabug/fxseq#2]
Just downloaded the 0.1 release VST3 and tried to load it in Bitwig 5.1 beta 3 on Linux. As soon as the plugin is added the audio engine crashes.

**Comment by ssabug** [comment]
Thank you for your feedback. 
The plugin has been tested on Bitwig 4.4 so far, if you have a previous bitwig version i am curious if it is working on your side.
Do you have any log or error message returned after the crash?
And which audio engine are you using ? The plugin has been tested with pipewire and jack so far.

**Comment by spectromas** [comment]
I have access to 5.0.11 and it crashes there too but in a slightly different way. In this version it happens in a way I've seen and reported a few times for various plugins (VCV Rack Pro, Speedrum)

![image](https://github.com/ssabug/fxseq/assets/6443372/a594e5a3-bc79-45ff-9cea-78c1139999ac)

I have attached the engine.log. The BitwigStudio.log doesn't appear to show anything related. 

[engine.log](https://github.com/ssabug/fxseq/files/13230130/engine.log)


This is with pipewire chosen as the audio output option in Bitwig.

**Comment by ssabug** [comment]
Thank you for the details.
Did you copy the plugin data with the ` ./Ressources/scripts/copy_plugin_data_linux.sh ` bash script?

**Comment by spectromas** [comment]
No, I'm an idiot! Sorry, I completely missed the instructions, must have been in a rush that day!

**Comment by ssabug** [comment]
Does the plugin works then?

**Comment by spectromas** [comment]
Yes, it does. Apologies for wasting your time.

**Comment by ssabug** [comment]
No problem, im happy to have feedback and to see the plugin is workin on someone else's computer.
Dont hesitate to make any return about the plugin's functionality, given most of the bugs  may be already listed in the HISTORY.md file .
